name: Cloud Health Watchdog
on: [push]

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Website Availability
        env:
          MY_URL: ${{ secrets.TRGET_URL }}
        run: |
          RESPONSE=$(curl -Ls -o /dev/null -w "%{http_code}" "$MY_URL")
          if [ "$RESPONSE" -eq 200 ]; then
            echo "SUCCESS: The target is healthy (Status 200)"
          else
            echo "CRITICAL: The target returned status $RESPONSE"
            exit 1
          fi
